import type { Metadata } from "next";
import { arsenal, oxygen_mono, nova_square, raleway } from "app/utils/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portfolio: Amanda Limon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arsenal} ${raleway} ${oxygen_mono} ${nova_square}`}>{children}</body>
    </html>
  );
}
