import type { Metadata } from "next";
import { arsenal, oxygen_mono, nova_square, raleway } from "app/utils/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Amanda Limon Portfolio",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string
  }
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={`${arsenal} ${raleway} ${oxygen_mono} ${nova_square}`}>{children}</body>
    </html>
  );
}
